# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='author_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
